name: CI with Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Java required for Sonar
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      # ✅ Sonar Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # ✅ Docker Build
      - name: Build Docker Image
        run: docker build -t devops-app .
